config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get '/help', to:'static_pages#help'
  get '/about', to:'static_pages#about'
  get '/contact', to:'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  # resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  # like機能
  resources :microposts do
    resources :likes, only: [:create, :destroy]
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :micropost, counter_cache: :likes_count
  belongs_to :user
  validates :user_id, { presence: true }
  validates :micropost_id, { presence: true }
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = Like.create(
      user_id: current_user.id,
      micropost_id: params[:micropost_id]
    )
    @likes = Like.where(micropost_id: params[:micropost_id])
    redirect_to root_url
  end

  def destroy
    like = Like.find_by(
      user_id: current_user.id,
      micropost_id: params[:micropost_id]
    )
    like.destroy
    @likes = Like.where(micropost_id: params[:micropost_id])
    redirect_to root_url
  end

end

app/views/likes/_like.html.erb
<% if micropost.like_user(current_user.id) %>
  <%= button_to micropost_like_path(likes, micropost_id: micropost.id),
                  method: :delete, id: "like-button", remote: true do %>
    <span class="fa fa-heart like-btn-unlike">
      <%= micropost.likes_count %>
    </span>
  <% end %>
<% else %>
  <%= button_to micropost_likes_path(micropost), id: "like-button", remote: true do %>
    <span class="fa fa-heart like-btn">
      <%= micropost.likes_count %>
    </span>
  <% end %>
<% end %>

app/views/likes/create.js.erb
$("#like-buttons").html("<%= j(render partial: 'like', locals: { micropost: micropost, likes: @likes, like: @like}) %>");

app/views/likes/destoy.js.erb
$("#like-buttons").html("<%= j(render partial: 'like', locals: { micropost: micropost, likes: @likes }) %>");